#!/usr/bin/env perl
#

# This step eliminates the skull and meninges by creating a coarse cortical
# surface then removing tissue lying outside of it. The surface produced here
# is a result of a deforming ellipsoid model that shrinks inward in an iterative
# fashion until it finds the pial surface of the cortex. It is not accurate
# enough to become the final pial surface in our corticometric analysis. But
# it does a decent job as a mask to exclude the skull and meninges.


use strict;
use warnings "all";
use MNI::Startup;
use MNI::FileUtilities qw(check_output_dirs);

# define input variables:

my $cls=$ARGV[0];
my $cortex=$ARGV[1];
my $skull_mask=$ARGV[2];
my $brain_mask=$ARGV[3];

# Directory for temporary files.

MNI::FileUtilities::check_output_dirs($TmpDir) or exit 1;

# Application of cortical_surface to mask out any remaining non-cortical
# tissue, if any, and the cerebellum. This step can help remove the eyes
# as well.

# run defrag before the cortical surface mask to remove dangling pieces
# of white and grey tissues. This will increase the accuracy of the
# cortical surface by preventing the surface to be attracted to non-
# desired tissues.

my $cls_defrag = "${TmpDir}/cls_defrag.mnc";

&run( "mincdefrag", $cls, $cls_defrag, 3, 6 );

&run( "mincdefrag", $cls_defrag, $cls_defrag, 2, 6 );

# cortical surface to mask out cerebellum and other non-cortical tissues

&run( "cortical_surface", $cls_defrag, $cortex, 1.5 );

# masking of brain with the cortical surface. No need to remove the boundary
# lines (from scan_object_to_volume) since the mask is very very tight.

&run( "surface_mask2", "-binary_mask", $cls, $cortex, $cls_defrag );
&run( "mincmath", "-clobber", "-mult", $cls_defrag, $skull_mask, $brain_mask );

#Execute a system call.

sub run {
  print "@_\n";
  system(@_)==0 or die "Command @_ failed with status: $?";
}

