#!/usr/bin/env perl
#

# Perform cortical measurements in native space.
# 1 - Transform cortical surfaces from Talairach to native
# 2 - Compute cortical thickness
# 3 - Blur cortical thickness on mid-surface
# 4 - Compute cortex area on gray surface

use strict;
use warnings "all";

use Getopt::Tabular;
use MNI::Startup;
use MNI::FileUtilities qw(check_output_dirs);

# --- set the help & usage strings ---
my $help = <<HELP;
Compute the cortical thickness and area in native space from the white and gray surfaces.
HELP

my $usage = <<USAGE;
Usage: $ProgramName [options] white.obj gray.obj output_thickness.txt output_area.txt
       $ProgramName -help to list options

USAGE

my $transform_xfm = undef;

my @options =
  ( @DefaultArgs,     # from MNI::Startup
    ['-transform', 'string', 1, \$transform_xfm,
     'transformation from native to stereotaxic (if surfaces in stx space)'],
  );

Getopt::Tabular::SetHelp( $help, $usage );

GetOptions( \@options, \@ARGV )
  or exit 1;
die "$usage\n" unless @ARGV == 5;

# define input variables:

my $white=$ARGV[0];
my $gray=$ARGV[1];
my $thickness=$ARGV[2];
my $stx_labels_masked=$ARGV[3];     # input - from animal
my $lobe_areas = $ARGV[4];          # output from cortex_area
my $lobes_thickness = $ARVG[5];     # output from region_thickness

# Directory for temporary files.

MNI::FileUtilities::check_output_dirs($TmpDir)
or exit 1;

# Apply inverse transformation to map to desired space.

$my white_stx = $white;
$my gray_stx = $gray;
$my white_native = $white;
$my gray_native = $gray;

if( defined $transform_xfm ) {
  $white_native = "${TmpDir}/white_trans.obj";
  $gray_native = "${TmpDir}/gray_trans.obj";
  my $inv_trans = "${TmpDir}/inv_trans.xfm";
  &run( "xfminvert", $transform_xfm, $inv_trans );
  &run( "transform_objects", $white, $inv_trans, $white_trans );
  &run( "transform_objects", $gray, $inv_trans, $gray_trans );
}

# Once the surfaces, thickness values and the ANIMAL labels have been produced,
# it is now possible to intersect the labels of the brain lobes with the
# cortical surfaces. This will allow the calculation of mean cortical thickness
# values for these lobes, as well as an estimate of cortical surface area for
# each lobe. All of this is done in native space.

# Compute the cortex area in new space.

# intersect ANIMAL volume segmentation with stx mid surface
# (NOTE: using the mid-surface should avoid having vertices 
#        of the gray surface interpolated as csf, since we
#        want the nearest brain tissue.)

my $midSurface_stx = "${TmpDir}/midSurfaceStx.obj";
&run( "average_surfaces", $midSurface_stx, "none", "none", 1, 
      $gray_stx, $white_stx );

my $stx_surface_labels = "${TmpDir}/animal_surface_labels.txt";
&run( "volume_object_evaluate", $stx_labels_masked, $midSurface_stx, 
      $stx_surface_labels );

# segment stx surface labels into lobes

my $stx_surface_lobes = "${TmpDir}/animal_surface_lobes.txt";
&run( "remap_to_lobes", $stx_surface_labels, $stx_surface_lobes );

# Define mesh areas at the nodes, applying the lobes on the native
# gray surface now. (This should probably be blurred too.)

&run( "cortex_area", "-surface", $gray_native, "-zone", $stx_surface_lobes,
      "-output", $lobe_areas );

# cortical thickness mapped onto the lobes

&run( "regional_thickness", $thickness, $stx_surface_lobes, 
      $lobes_thickness );

#Execute a system call.

sub run {
  print "@_\n";
  system(@_)==0 or die "Command @_ failed with status: $?";
}

