#!/usr/bin/env perl
#
# generate tal reg statistic uses threshold,mask,input,output



use strict;
use warnings "all";
use File::Basename;



my @args = ("mincstats","-clobber", "-max",$ARGV[0]);
print @args;
my $result = `@args`;
my $binstring="";
my @line = split/\s+/,$result;

my $numbins =  $line[1];

for (my $i=0;$i<($numbins+1);$i++){
 $binstring ="${binstring}${i},";
 }
 
 #print $binstring;
#mincstats -sum -mask_binvalue 0,1,2,3, -mask ../../../../../IMPORTANT_IMAGES/T1_QC_mask.mnc mni_icbm_00100_qc_outlier_image.mnc 

 @args = ("mincstats","-sum","-mask_binvalue",$binstring,"-mask",$ARGV[0],$ARGV[1]);
 print @args;
 $result = `@args`;
 
 @line = split/\s+/,$result;
 print @line;
 print $line[1];
 open(myFile,">$ARGV[2]");
  for  ( my $i=0;$i<($numbins+1);$i++){
 print myFile "$i\t$line[5+$i*6]\n";
 }
 close(myFile);
# 
# 
# 
# 
# @args = ("rm","${ARGV[2]}_temp");
# #print @args;
# system(@args) == 0 or die "system @args failed: $?";

