#!/usr/bin/env perl
#

# This step eliminates the skull and meninges by creating a coarse cortical
# surface then removing tissue lying outside of it. The surface produced here
# is a result of a deforming ellipsoid model that shrinks inward in an iterative
# fashion until it finds the pial surface of the cortex. It is not accurate
# enough to become the final pial surface in our corticometric analysis. But
# it does a decent job as a mask to exclude the skull and meninges.


use strict;
use warnings "all";
use File::Basename;
use Math::BigFloat;

# define input variables:

my $maskOption=$ARGV[0];
my $prefix=$ARGV[1];
my $dsid=$ARGV[2];
my $temp_dir=$ARGV[3];
my $cls_tmp=$ARGV[4];
my $t1_tal_mnc=$ARGV[5];
my $cortex=$ARGV[6];
my $cls_masked=$ARGV[7];
my $brain_mask=$ARGV[8];
my $brain_maskD=$ARGV[9];

# define internal variables:

my $bet_brain_prefix = "${temp_dir}/${prefix}_${dsid}_bet_brain";
my $bet_brain_mask = "${bet_brain_prefix}_mask.mnc";
my $bet_brain_mask_temp = "${bet_brain_prefix}_mask_temp.mnc";
my $cls_tmp_bet = "${temp_dir}/${prefix}_${dsid}_brain_mask_cls_bet.mnc";
my $cls_tmp_defrag = "${temp_dir}/${prefix}_${dsid}_cls_tmp_defrag.mnc";


# mask non-cortical tissues using mincbet

if( $maskOption eq "BET" ) {

  # run FSL bet on the classified image (output is "${bet_brain_prefix}_mask.mnc")

  &run( "mincbet", $cls_tmp, $bet_brain_prefix, "-n", "-m", "-f", "0.44" );

  # getting mincbet data in correct form

  &run( "mincreshape","-clobber","-byte", $bet_brain_mask, $bet_brain_mask_temp );

  # use mincbet mask for skull stripping 

  &run( "mincmath", "-clobber", "-mult", $cls_tmp, $bet_brain_mask_temp, $cls_tmp_bet );

  # cleaning mincbet temp files

  &run( "rm", "-f", $bet_brain_mask, $bet_brain_mask_temp );

} else {

  &run( "cp", "-f", $cls_tmp, $cls_tmp_bet );

}

# run defrag before the cortical surface mask to remove dangling pieces
# of white and grey tissues. This will increase the accuracy of the
# cortical surface by preventing the surface to be attracted to non-
# desired tissues.

&run( "mincdefrag", $cls_tmp_bet, $cls_tmp_defrag, 3, 6 );

&run( "mincdefrag", $cls_tmp_defrag, $cls_tmp_defrag, 2, 6 );

# cortical surface to mask out cerebellum and other non-cortical tissues

&run( "cortical_surface", $cls_tmp_defrag, $cortex, 1.5 );

# masking of brain with the cortical surface

&run( "surface_mask2", $cls_tmp_defrag, $cortex, $cls_masked );

# creation of binary mask

&run( "msd_masks", "-clobber", "-dilated_mask", $brain_maskD, $t1_tal_mnc, 
      $cortex, $brain_mask );

# cleaning masking temp files

&run( "rm", "-f", $cls_tmp_bet, $cls_tmp_defrag );


#Execute a system call.

sub run {
  print "@_\n";
  system(@_)==0 or die "Command @_ failed with status: $?";
}

